version: '3.0'

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/public_html
    networks:
      - network1
    depends_on:
      - php
      - mysql1
  php:
    container_name: php
    build:
      context: ./docker/php
    volumes:
      - ./html:/var/www/public_html
    networks:
      - network1
    depends_on:
      - mysql1
  mysql1:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - network1
  phpmyadmin:
    container_name: phpma
    image: phpmyadmin
    ports:
      - 1500:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - network1
    depends_on:
      - mysql1
networks:
  network1:
    name: network1
